name: Build & Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -DskipTests package

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: cne-ws25

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          IMAGE="europe-west3-docker.pkg.dev/cne-ws25/pdf-repo/pdf-service:latest"
          docker build -t "$IMAGE" .

      - name: Push Docker image
        run: |
          IMAGE="europe-west3-docker.pkg.dev/cne-ws25/pdf-repo/pdf-service:latest"
          docker push "$IMAGE"

      - name: Deploy API service
        run: |
          IMAGE="europe-west3-docker.pkg.dev/cne-ws25/pdf-repo/pdf-service:latest"
          gcloud run deploy pdf-service \
            --image "$IMAGE" \
            --platform managed \
            --region europe-west3 \
            --allow-unauthenticated
