name: Build & Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      SERVICE_NAME: pdf-service
      IMAGE: europe-west3-docker.pkg.dev/cne-ws25/pdf-service/app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Authenticate gcloud
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
          gcloud config set project $PROJECT_ID



      - name: Deploy API service
        run: |
          gcloud run deploy pdf-service \
            --region europe-west3 \
            --source . \
            --allow-unauthenticated \
            --project cne-ws25

      - name: Deploy Worker service
        run: |
          gcloud run deploy pdf-worker \
            --region europe-west3 \
            --source . \
            --allow-unauthenticated \
            --project cne-ws25
